name: CCKA CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 termcolor

      - name: Lint with flake8
        run: |
          flake8 backend tests --max-line-length=120

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=$PWD
          pytest -v --disable-warnings
